public class Util {

    public static final Collection collection = new Collection();
    public static final Cnpj cnpj = new Cnpj();
    public static final Cpf cpf = new Cpf();

    public class Collection{

    }

    public class Cnpj{

        public Boolean isValid(String cnpj){
            return null;
        }

        public String format(String cnpj){
            return null;
        }

        public String clear(String cnpj){
            return null;
        }

    }

    public class Cpf{

        public Boolean isValid(String cpf){
            return null;
        }

        public String format(String cpf){
            return null;
        }

        public String clear(String cnpj){
            return null;
        }

    }
    
}
